version: 2.0
jobs:
    py36:
        working_directory: ~/circleci
        docker:
            - image: circleci/python
              environment:
                PYTHON_VER: 3.6

        steps:
            - checkout

            - run: |
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O conda.sh
                bash conda.sh -b -p ~/conda
                ~/conda/bin/conda config --system --add channels conda-forge
                ~/conda/bin/conda config --system --add channels coecms
                ~/conda/bin/conda update conda
                ~/conda/bin/conda install --yes conda-build conda-verify

            - run: |
                ~/conda/bin/conda build -c coecms conda --python=${PYTHON_VER}

            - run: |
                mkdir ~/artefacts
                cp $(~/conda/bin/conda build conda --python=${PYTHON_VER} --output) ~/artefacts

            - persist_to_workspace:
                root: ~/artefacts
                paths: '*'

    publish:
        working_directory: /circleci
        docker:
            - image: scottwales/conda-build
        steps:
            - attach_workspace:
                at: /artefacts

            - run:
                anaconda --token "${ANACONDA_TOKEN}" upload --user "${ANACONDA_USER}" /artefacts/*.tar.bz2

workflows:
    version: 2
    build_and_publsh:
        jobs:
            - py36:
                filters:
                    tags:
                        only: /.*/

            - publish:
                requires:
                    - py36
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
