name: ncimonitor

channels:
    - coecms
    - conda-forge
    - defaults

dependencies:
    - python
    - numpy
    - dask
    - distributed
    - xarray
    - netcdf4
    - joblib
    - tqdm
    - sqlalchemy

