package:
    name: cosima-cookbook
    version: latest

source:
    git_rev: master
    git_url: https://github.com/COSIMA/cosima-cookbook

#build:
#    number: 0
#    skip: true
#    #script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - dask
        - distributed
        - xarray
        - netcdf4
        - joblib
        - tqdm

about:
    home: http://cosima-cookbook.readthedocs.io
    license: Apache License 2.0
    license_file: LICENSE
