name: Testing

on:
  push:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Code formatting
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "--check --verbose cosima_cookbook test"

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9]
        sqa-version: ['<1.4', '==1.4']
        fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install '.[build]'
          python -m pip install "sqlalchemy${{ matrix.sqa-version}}"
      - name: Unit tests
        run: |
          python -m pytest test
